version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    ports:
      - "8000:80" # Laravel dispo sur http://localhost:8000
    volumes:
      - .:/var/www/html
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: true
      APP_KEY: base64:YOUR_APP_KEY
      DB_CONNECTION: pgsql
      DB_HOST: db
      DB_PORT: 5432
      DB_DATABASE: laravel
      DB_USERNAME: postgres
      DB_PASSWORD: root

  db:
    image: postgres:15
    container_name: laravel_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: laravel
    ports:
      - "5433:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data: 