[phases.setup]
nixPkgs = ["php", "composer", "postgresql"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[phases.build]
cmds = [
    "php artisan key:generate",
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache",
    "php artisan optimize"
]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/" 