[phases.setup]
# Installer PHP 8.2 + extensions nécessaires à Laravel avec PostgreSQL
nixPkgs = [
    "php82",
    "php82Extensions.curl",
    "php82Extensions.mbstring",
    "php82Extensions.xml",
    "php82Extensions.pgsql",
    "php82Extensions.pdo_pgsql",
    "php82Extensions.zip",
    "php82Extensions.fileinfo",
    "php82Extensions.gd",
    "php82Extensions.exif",
    "php82Extensions.intl",
    "php82Extensions.bcmath"
]

[phases.build]
# Installer les dépendances Laravel
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
# Lancer Laravel avec Apache
cmd = "vendor/bin/heroku-php-apache2 public/"
