[phases.setup]
nixPkgs = ["php82", "php82Extensions.curl", "php82Extensions.mbstring", "php82Extensions.xml", "php82Extensions.pgsql", "php82Packages.composer", "nodejs", "npm"]

[phases.build]
cmds = ["composer install --ignore-platform-reqs --no-dev --optimize-autoloader", "npm ci"]

[start]
cmd = "vendor/bin/heroku-php-apache2 public/" 